server:
 port: 8888
spring:
 application:
  name: config-server
 cloud:
  config:
   server:
    git:
     uri: https://github.com/Mmglz/config-server.git
    default-label: master
    search-paths:
    - '*service*'
